# Ansible
# ansible_user: root

# Kubernetes
kube_version: v1.13.0
token: b0f7b8.8d1767876297d85c

# 1.8.x feature: --feature-gates SelfHosting=true
init_opts: ""

# Any other additional opts you want to add..
#kubeadm_opts: ""
# For example:
kubeadm_opts: '--apiserver-cert-extra-sans "10.8.0.1,167.114.98.168"'

#service_cidr: "10.96.0.0/12"
pod_network_cidr: "10.244.0.0/16"

# Network implementation('flannel', 'calico')
network: flannel

# Change this to an appropriate interface, preferably a private network.
# For example, on DigitalOcean, you would use eth1 as that is the default private network interface.
network_interface: ""

enable_dashboard: no

# A list of insecure registries you might need to define
insecure_registries: ['s167.com:30100']
# insecure_registries: ['gcr.io']

systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon
